language: node_js
node_js:
  - 12

services:
  - docker

before_install:
  - echo "nothing needs to be checked before install"
# Pre-testing installs
install:
  - echo "nothing needs to be installed"
  
# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  - docker --version
  - docker build -f udagram-api-feed/Dockerfile -t  einstein16/udagram-api-feed:v1 udagram-api-feed
  - docker build -f udagram-api-user/Dockerfile -t  einstein16/udagram-api-user:v1 udagram-api-user
  - docker build -f udagram-frontend/Dockerfile -t  einstein16/udagram-frontend:v1 udagram-frontend
  - docker build -f udagram-reverseproxy/Dockerfile -t  einstein16/udagram-reverseproxy:v1 udagram-reverseproxy


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push einstein16/udagram-api-feed:v1
  - docker push einstein16/udagram-api-user:v1
  - docker push einstein16/udagram-frontend:v1
  - docker push einstein16/udagram-reverseproxy:v1