
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      restartPolicy: Always
      containers:
        - name: udagram-reverseproxy
          imagePullPolicy: Always
          image: einstein16/udagram-reverseproxy:v1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 512m
            requests:
              cpu: 256m